### ISSUE TITLE
Missing zipcodes

### ISSUE THREAD

**Issue by avishapiro** [buckmaxwell/zippy#1]
There are over 6000 missing US zipcodes in the database. What are the sources? Many of the missing are in Washington, D.C. but another (17270) is in Pennsylvania.

```
zipcode.isequal('20001').zip

---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-70-58347e736241> in <module>()
----> 1 zipcode.isequal('23001').zip

AttributeError: 'NoneType' object has no attribute 'zip'
```

**Comment by buckmaxwell** [comment]
Thanks for letting me know Avi.  The zipcodes are taken from a csv released on a governement website around 2006 I think so it is quite out of date and I am not surprised it is missing zip codes.  I can send you the csv if you like. Do you have another source to build the database from that would be better?

I haven't looked at this for a while, but I'd like to update it so that it works for all zipcodes if I can.

**Comment by avishapiro** [comment]
Hi Max,

I was surprised not to find a standard python module to fetch zipcode
information and liked yours and your documentation. Another package,
pyzipcode, uses 2004 data. Actually, reading more carefully, the change log
says it uses an updated API for zips. I only needed a city name associated
with the zipcode and I found sufficient data for download at
http://www.unitedstateszipcodes.org/.

Cheers,
Avi

**Comment by Bhhitt** [comment]
Just as an FYI buckmaxwell, I found some missing ones also. I went with a different package that had the few I couldnt find, but I liked this package. Saying this so that you know that people are looking at this package.

**Comment by hangfei** [comment]
I found a missing one: 54901

**Comment by hangfei** [comment]
For zipcodes csv file, what fields of info do you need for zip code?

**Comment by buckmaxwell** [comment]
Thanks Boyd. Looking to fix up this package in the next few weeks.

**Comment by dreyco676** [comment]
post the source of the input file and I can try to make an updater function.

**Comment by suokunlong** [comment]
There is a similar lib in R: https://cran.r-project.org/web/packages/zipcode/
It uses csv file from http://federalgovernmentzipcodes.us/
This source claims that the data was updated in 2012.

**Comment by buckmaxwell** [comment]
A lot of people seem to use this package and it would be nice to be able to keep it up to date.  I'll see what I can do over the next few days to get it updated.

**Comment by ChrisMuir** [comment]
FYI I get zero results for:
`zipcode.islike('60')`
Which is most/all of Chicago.

I see you're working on it, so not trying to pile on, just a friendly heads up. Other than that I think the package is great, thanks!

**Comment by kevinsa5** [comment]
To add to the test suite, most or all of NC is missing as well --
 `zipcode.islike("27")` and `zipcode.islike("28")`

**Comment by ibu2710** [comment]
For Indian ZIP codes... in major cities also it shows couldn't find zip code. Is there any other similar libraries which provides all the updated zip codes...

**Comment by buckmaxwell** [comment]
@ibrahim-appgodz , right now only zipcodes in usa are supported.  If you have a source where I can find Indian zipcode information perhaps we can update the package.

**Comment by buckmaxwell** [comment]
Hello all,  if anyone is interested in being part of development for the
next major version of this please let me know - I can add you to our slack
channel.  A lot of people use this project and I'd like for it to be up to
date and reliable very soon :D

Max

**Comment by buckmaxwell** [comment]
Those interested, please send me an email at maxbuckdeveloper@gmail.com

Thanks,
Max

**Comment by sjachim** [comment]
How about using this: http://federalgovernmentzipcodes.us/ ?
It seems to be well curated by people knowing a thing about stats.

**Comment by buckmaxwell** [comment]
Thanks for the tip.. I will look into this

**Comment by buckmaxwell** [comment]
we finally have an update to this issue. zipcodes in 3.0.0 are up to date. There is also a way (described in the README.md) to keep the zip database up to date by running a monthly cron job.
