### ISSUE TITLE
Import Error

### ISSUE THREAD

**Issue by huileiw** [buckmaxwell/zippy#11]
In Python 3.5 environment, used 'pip3 install zipcode' to install. I'm getting below error at import zipcode: 

In [1]: import zipcode
  File "/usr/local/lib/python3.5/dist-packages/zipcode/__init__.py", line 52
    self.timezone = zip_tuple[_TIMEZONE]
                                        ^
TabError: inconsistent use of tabs and spaces in indentation

**Comment by buckmaxwell** [comment]
Hmm. Trying to replicate now...

**Comment by buckmaxwell** [comment]
Thanks, I was able to replicate.  making a fix now.

**Comment by buckmaxwell** [comment]
@huileiw , sorry you had trouble.  I've made a fix, please ensure it works.

I suggest reinstalling with

```
pip3 uninstall zipcode
pip3 install zipcode --no-cache-dir
```
