### ISSUE TITLE
Exception: ZIPCODE_CONNECTION_STRING not set

### ISSUE THREAD

**Issue by gjthompson1** [buckmaxwell/zippy#16]
I am getting this error when trying to do

Python 3.6.5

For zipcode 
4.0.0 

zipcode 3.0.1 seems to work...

```
import zipcode
---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
/usr/local/lib/python3.6/site-packages/zipcode/__init__.py in <module>()
     15 try:
---> 16     conn_str = os.environ['ZIPCODE_CONNECTION_STRING']
     17 except KeyError:

/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/lib/python3.6/os.py in __getitem__(self, key)
    668             # raise KeyError with the original key value
--> 669             raise KeyError(key) from None
    670         return self.decodevalue(value)

KeyError: 'ZIPCODE_CONNECTION_STRING'

During handling of the above exception, another exception occurred:

Exception                                 Traceback (most recent call last)
<ipython-input-2-1c1e8d2b861e> in <module>()
----> 1 import zipcode

/usr/local/lib/python3.6/site-packages/zipcode/__init__.py in <module>()
     16     conn_str = os.environ['ZIPCODE_CONNECTION_STRING']
     17 except KeyError:
---> 18     raise Exception('ZIPCODE_CONNECTION_STRING not set, \n'
     19             'http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine')
     20

Exception: ZIPCODE_CONNECTION_STRING not set,
http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine
```

**Comment by buckmaxwell** [comment]
did you set a zipcode connection string via the readme?  You gotta do something like, 

```
# set connection string, we use sqlite as an example (but use postgres in production!)
echo 'ZIPCODE_CONNECTION_STRING=sqlite:///zipcode.db' >> ~/.bash_profile
source ~/.bash_profile
```

to see which connection string to use based on the database you are using, check here - http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine. 

Please be aware that in order to use zipcode 4 (which is great, and you should) be sure to follow the readme entirely for installation as the db is separate, unlike zipcode 3.

**Comment by agrushevsky** [comment]
*MacOS
I am confused, I am using sqlite, I have this written out in bash_profile

> echo 'ZIPCODE_CONNECTION_STRING=sqlite:///Users/lamer/zipcode.db'


I have a zipcode.db at that location
When I run build_zipcode_database
> I get this error
> (three) bash-3.2$ build_zipcode_database
> Traceback (most recent call last):
>   File "/anaconda3/envs/three/lib/python3.6/site-packages/zipcode/__init__.py", line 16, in <module>
>     conn_str = os.environ['ZIPCODE_CONNECTION_STRING']
>   File "/anaconda3/envs/three/lib/python3.6/os.py", line 669, in __getitem__
>     raise KeyError(key) from None
> KeyError: 'ZIPCODE_CONNECTION_STRING'
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/anaconda3/envs/three/bin/build_zipcode_database", line 6, in <module>
>     from zipcode import Session, Zip, Base, engine
>   File "/anaconda3/envs/three/lib/python3.6/site-packages/zipcode/__init__.py", line 18, in <module>
>     raise Exception('ZIPCODE_CONNECTION_STRING not set, \n'
> Exception: ZIPCODE_CONNECTION_STRING not set, 
> http://docs.sqlalchemy.org/en/latest/core/engines.html#sqlalchemy.create_engine
> (three) bash-3.2$ 

What am I doing wrong?

**Comment by buckmaxwell** [comment]
@agrushevsky  -- you want
```bash
export 'ZIPCODE_CONNECTION_STRING=sqlite:///Users/lamer/zipcode.db'
```
(export not echo) if you are writing it in bash profile.

**Comment by raghuram-kukun** [comment]
@buckmaxwell I followed the steps outlined in the README. I keep getting the ZIPCODE_CONNECTION_STRING not set error. I also looked at the link pointed to find out the connection string. I was not able to understand that. Could you please help?

**Comment by raghuramdr** [comment]
@buckmaxwell I followed the instructions in the README, but the db file is never created on the path I specify. Is there something that I am missing out on?

**Comment by buckmaxwell** [comment]
Maybe.

1. do you have sqlite installed?
2. did build_zipcode_database run without error?
3. what is your connection string and what is the path you are expecting the db will be created at (only w sqlite will a file be created)
