### ISSUE TITLE
How to install in Windows Environment?

### ISSUE THREAD

**Issue by cywei23** [buckmaxwell/zippy#18]
When I follow through the instructions to install, the windows command won't let me run the 'source ~/.bash_profile'. Any suggestion about how to overcome that? Also, can you elaborate how to run the 'build_zipcode_database'? Where can I find that after pip install zipcode? Thanks!

**Comment by buckmaxwell** [comment]
If you are using windows command prompt you are probably not using bash. Most windows users get around this by using Cygwin https://www.cygwin.com. Please let me know if this works.
