### ISSUE TITLE
zipcode cannot support multithread with pip install

### ISSUE THREAD

**Issue by caoyi0905** [buckmaxwell/zippy#8]
When I pip install this package by `pip install zipcode`, it cannot support multithread yet.Hope you can update its version and upload latest code to pypi. 

Thanks for making such useful package!

**Comment by jayliew** [comment]
Same here. `SQLite objects created in a thread can only be used in that same thread.The object was created in thread id 123145455906816 and this is thread id 123145461161984`

**Comment by jayliew** [comment]
For anyone else having the same problem, use `pip` to install directly from github like this `pip install -e git://github.com/buckmaxwell/zipcode.git#egg=Package`

**Comment by seanpianka** [comment]
@jayliew @caoyi0905 If you're still having issues with multi-threading, feel free to check out [my "zipcodes" library](https://github.com/seanpianka/Zipcodes) which has removed the SQLite dependency.

**Comment by buckmaxwell** [comment]
To support a greater number of users, porting the sqlite database to postgres or another db would solve your issue.  I'll make an issue to create instructions for using this package with a real database.
